replicaCount: 2

image:
  repository: ghcr.io/ahmedbmohamed/devsecops-gitops-lab
  # The CI pipeline updates this tag automatically after each successful build
  tag: "ac53bd0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

securityContext:
  runAsNonRoot: true
  runAsUser: 10001
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL
